let mongoose = require("mongoose");

let usiq = new mongoose.Schema({
    "Language": { 
        type: String, 
        required: true 
    },
    "Level": { 
        type: String, 
        required: true // e.g., "Fresher" or "Experienced"
    },
    
    // Stores the array of questions generated by AI and the user's responses
    "Exam QnA": [
        {
            "Question": { type: String, required: true },
            "User Answer": { type: String, default: "" }
        }
    ],
    
    // Anti-cheating / Full-screen violation tracker
    "Violations": {
        "Fullscreen Exited": { type: Boolean, default: false },
        "Exit Count": { type: Number, default: 0 } // Tracks how many times they tried to leave
    },
    
    // AI Feedback and Analytics with built-in 0-100 validation
    "Communication": { 
        type: Number, 
        default: 0,
        min: [0, "Score cannot be less than 0"],
        max: [100, "Score cannot exceed 100"]
    },
    "Technical Accuracy": { 
        type: Number, 
        default: 0,
        min: [0, "Score cannot be less than 0"],
        max: [100, "Score cannot exceed 100"]
    },
    "Confidence": { 
        type: Number, 
        default: 0,
        min: [0, "Score cannot be less than 0"],
        max: [100, "Score cannot exceed 100"]
    },
    "Total score": { 
        type: Number, 
        default: 0,
        min: [0, "Score cannot be less than 0"],
        max: [100, "Score cannot exceed 100"]
    },
    
    // Tracks when the mock test was taken
    "Created At": {
        type: Date,
        default: Date.now
    }
});

let umiq = mongoose.model("ai_generated_interview_questions", usiq);
module.exports = umiq;